# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions


from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyProfiles(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.ProfileVerdict"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyProfiles", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.ProfileVerdict"], __result__)

    def ExtractItems(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["types.NewsletterItem"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractItems", llm_response=llm_response, mode="request")
        return typing.cast(typing.List["types.NewsletterItem"], __result__)

    def SelectNotableItems(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List[int]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SelectNotableItems", llm_response=llm_response, mode="request")
        return typing.cast(typing.List[int], __result__)

    def SelectProductLink(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.ProductLinkChoice:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SelectProductLink", llm_response=llm_response, mode="request")
        return typing.cast(types.ProductLinkChoice, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def ClassifyProfiles(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.ProfileVerdict"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ClassifyProfiles", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.ProfileVerdict"], __result__)

    def ExtractItems(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List["stream_types.NewsletterItem"]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="ExtractItems", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List["stream_types.NewsletterItem"], __result__)

    def SelectNotableItems(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> typing.List[int]:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SelectNotableItems", llm_response=llm_response, mode="stream")
        return typing.cast(typing.List[int], __result__)

    def SelectProductLink(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.ProductLinkChoice:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SelectProductLink", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.ProductLinkChoice, __result__)

    