# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (5)
# #########################################################################

class NewsletterItem(BaseModel):
    kind: typing.Optional[types.NewsletterItemKind] = None
    name: typing.Optional[str] = Field(default=None, description='Product name, or the article\'s title')
    description: typing.Optional[str] = Field(default=None, description='Concise phrase: what it is and does, usable verbatim as a web search query')
    url: typing.Optional[str] = Field(default=None, description='For an Article, the href of its link, copied verbatim including any tracking redirect. Omit for a Product.')

class ProductLinkChoice(BaseModel):
    index: typing.Optional[int] = Field(default=None, description='1-based index of the best first-party result, or 0 if none qualifies')
    confidence: typing.Optional[float] = Field(default=None, description='0.0 - 1.0')

class ProfileInput(BaseModel):
    handle: typing.Optional[str] = Field(default=None, description='Substack owner handle, echoed back in the verdict')
    name: typing.Optional[str] = Field(default=None, description='Publication name')
    description: typing.Optional[str] = Field(default=None, description='Publication hero text and/or author bio, if known')

class ProfileVerdict(BaseModel):
    handle: typing.Optional[str] = Field(default=None, description='Must exactly match the input handle')
    isAiRelated: typing.Optional[bool] = None
    confidence: typing.Optional[int] = Field(default=None, description='0-100 confidence that AI/ML/LLMs is the PRIMARY focus')

class SearchCandidate(BaseModel):
    title: typing.Optional[str] = None
    url: typing.Optional[str] = None
    snippet: typing.Optional[str] = None

# #########################################################################
# Generated type aliases (0)
# #########################################################################
