# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ArticleInput": types.ArticleInput,
    "stream_types.ArticleInput": stream_types.ArticleInput,

    "types.CategorizeAndTagResult": types.CategorizeAndTagResult,
    "stream_types.CategorizeAndTagResult": stream_types.CategorizeAndTagResult,

    "types.ClassifyKindResult": types.ClassifyKindResult,
    "stream_types.ClassifyKindResult": stream_types.ClassifyKindResult,

    "types.ExtractedLink": types.ExtractedLink,
    "stream_types.ExtractedLink": stream_types.ExtractedLink,

    "types.NewsletterItem": types.NewsletterItem,
    "stream_types.NewsletterItem": stream_types.NewsletterItem,

    "types.ProductLinkChoice": types.ProductLinkChoice,
    "stream_types.ProductLinkChoice": stream_types.ProductLinkChoice,

    "types.ProfileInput": types.ProfileInput,
    "stream_types.ProfileInput": stream_types.ProfileInput,

    "types.ProfileVerdict": types.ProfileVerdict,
    "stream_types.ProfileVerdict": stream_types.ProfileVerdict,

    "types.ScoredArticle": types.ScoredArticle,
    "stream_types.ScoredArticle": stream_types.ScoredArticle,

    "types.SearchCandidate": types.SearchCandidate,
    "stream_types.SearchCandidate": stream_types.SearchCandidate,

    "types.TagOption": types.TagOption,
    "stream_types.TagOption": stream_types.TagOption,

    "types.TitleFix": types.TitleFix,
    "stream_types.TitleFix": stream_types.TitleFix,


    "types.ArticleCategory": types.ArticleCategory,

    "types.ArticleKind": types.ArticleKind,

    "types.NewsletterItemKind": types.NewsletterItemKind,

}