# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.NewsletterItem": types.NewsletterItem,
    "stream_types.NewsletterItem": stream_types.NewsletterItem,

    "types.ProductLinkChoice": types.ProductLinkChoice,
    "stream_types.ProductLinkChoice": stream_types.ProductLinkChoice,

    "types.ProfileInput": types.ProfileInput,
    "stream_types.ProfileInput": stream_types.ProfileInput,

    "types.ProfileVerdict": types.ProfileVerdict,
    "stream_types.ProfileVerdict": stream_types.ProfileVerdict,

    "types.SearchCandidate": types.SearchCandidate,
    "stream_types.SearchCandidate": stream_types.SearchCandidate,


    "types.NewsletterItemKind": types.NewsletterItemKind,

}