# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

from . import types
from . import stream_types


type_map = {

    "types.ArticleInput": types.ArticleInput,
    "stream_types.ArticleInput": stream_types.ArticleInput,

    "types.CategoryMatch": types.CategoryMatch,
    "stream_types.CategoryMatch": stream_types.CategoryMatch,

    "types.CategoryOption": types.CategoryOption,
    "stream_types.CategoryOption": stream_types.CategoryOption,

    "types.DedupMatch": types.DedupMatch,
    "stream_types.DedupMatch": stream_types.DedupMatch,

    "types.ExistingArticle": types.ExistingArticle,
    "stream_types.ExistingArticle": stream_types.ExistingArticle,

    "types.ExtractedLink": types.ExtractedLink,
    "stream_types.ExtractedLink": stream_types.ExtractedLink,

    "types.NewsletterProduct": types.NewsletterProduct,
    "stream_types.NewsletterProduct": stream_types.NewsletterProduct,

    "types.ProductLinkChoice": types.ProductLinkChoice,
    "stream_types.ProductLinkChoice": stream_types.ProductLinkChoice,

    "types.ProfileInput": types.ProfileInput,
    "stream_types.ProfileInput": stream_types.ProfileInput,

    "types.ProfileVerdict": types.ProfileVerdict,
    "stream_types.ProfileVerdict": stream_types.ProfileVerdict,

    "types.SearchCandidate": types.SearchCandidate,
    "stream_types.SearchCandidate": stream_types.SearchCandidate,

    "types.TitleFix": types.TitleFix,
    "stream_types.TitleFix": stream_types.TitleFix,


    "types.ArticleKind": types.ArticleKind,

}