# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from enum import Enum


from pydantic import BaseModel, ConfigDict, Field


import baml_py

CheckT = typing_extensions.TypeVar('CheckT')
CheckName = typing_extensions.TypeVar('CheckName', bound=str)

class Check(BaseModel):
    name: str
    expression: str
    status: str
class Checked(BaseModel, typing.Generic[CheckT, CheckName]):
    value: CheckT
    checks: typing.Dict[CheckName, Check]

def get_checks(checks: typing.Dict[CheckName, Check]) -> typing.List[Check]:
    return list(checks.values())

def all_succeeded(checks: typing.Dict[CheckName, Check]) -> bool:
    return all(check.status == "succeeded" for check in get_checks(checks))
# #########################################################################
# Generated enums (1)
# #########################################################################

class NewsletterItemKind(str, Enum):
    Product = "Product"
    Article = "Article"

# #########################################################################
# Generated classes (5)
# #########################################################################

class NewsletterItem(BaseModel):
    kind: NewsletterItemKind
    name: str = Field(description='Product name, or the article\'s title')
    description: str = Field(description='Concise phrase: what it is and does, usable verbatim as a web search query')
    url: typing.Optional[str] = Field(default=None, description='For an Article, the href of its link, copied verbatim including any tracking redirect. Omit for a Product.')

class ProductLinkChoice(BaseModel):
    index: int = Field(description='1-based index of the best first-party result, or 0 if none qualifies')
    confidence: float = Field(description='0.0 - 1.0')

class ProfileInput(BaseModel):
    handle: str = Field(description='Substack owner handle, echoed back in the verdict')
    name: str = Field(description='Publication name')
    description: typing.Optional[str] = Field(default=None, description='Publication hero text and/or author bio, if known')

class ProfileVerdict(BaseModel):
    handle: str = Field(description='Must exactly match the input handle')
    isAiRelated: bool
    confidence: int = Field(description='0-100 confidence that AI/ML/LLMs is the PRIMARY focus')

class SearchCandidate(BaseModel):
    title: str
    url: str
    snippet: str

# #########################################################################
# Generated type aliases (0)
# #########################################################################
