// This file is auto-generated by @hey-api/openapi-ts

export const AgentArticleCreateSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        publisher_slug: {
            type: 'string',
            title: 'Publisher Slug'
        },
        score: {
            type: 'integer',
            maximum: 100,
            minimum: 1,
            title: 'Score'
        },
        kind: {
            '$ref': '#/components/schemas/ArticleKind',
            default: 'blog'
        },
        categories: {
            items: {
                '$ref': '#/components/schemas/Category'
            },
            type: 'array',
            title: 'Categories'
        },
        summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary'
        },
        content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        published_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published At'
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags'
        }
    },
    type: 'object',
    required: ['url', 'title', 'publisher_slug', 'score'],
    title: 'AgentArticleCreate'
} as const;

export const AgentArticleCreatedSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        score: {
            type: 'integer',
            title: 'Score'
        },
        publisher_slug: {
            type: 'string',
            title: 'Publisher Slug'
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags'
        },
        embedded: {
            type: 'boolean',
            title: 'Embedded'
        }
    },
    type: 'object',
    required: ['id', 'url', 'title', 'score', 'publisher_slug', 'tags', 'embedded'],
    title: 'AgentArticleCreated'
} as const;

export const AgentPublisherSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        kind: {
            '$ref': '#/components/schemas/PublisherKind'
        },
        type: {
            '$ref': '#/components/schemas/PublisherType'
        },
        trust: {
            '$ref': '#/components/schemas/TrustLevel'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        links: {
            additionalProperties: {
                type: 'string'
            },
            propertyNames: {
                '$ref': '#/components/schemas/LinkPlatform'
            },
            type: 'object',
            title: 'Links'
        }
    },
    type: 'object',
    required: ['id', 'slug', 'name', 'kind', 'type', 'trust', 'is_active'],
    title: 'AgentPublisher'
} as const;

export const AgentTagSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['id', 'slug', 'name'],
    title: 'AgentTag'
} as const;

export const AnalyticsEventCreateSchema = {
    properties: {
        event: {
            type: 'string',
            title: 'Event',
            default: 'pageview'
        },
        path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Path'
        },
        referrer: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Referrer'
        },
        visitor_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Visitor Id'
        },
        props: {
            additionalProperties: true,
            type: 'object',
            title: 'Props'
        }
    },
    type: 'object',
    title: 'AnalyticsEventCreate'
} as const;

export const ArticleFacetsSchema = {
    properties: {
        publishers: {
            items: {
                '$ref': '#/components/schemas/PublisherFacet'
            },
            type: 'array',
            title: 'Publishers'
        },
        tags: {
            items: {
                '$ref': '#/components/schemas/TagFacet'
            },
            type: 'array',
            title: 'Tags'
        }
    },
    type: 'object',
    required: ['publishers', 'tags'],
    title: 'ArticleFacets'
} as const;

export const ArticleKindSchema = {
    type: 'string',
    enum: ['blog', 'product', 'announcement', 'repo', 'paper', 'model'],
    title: 'ArticleKind'
} as const;

export const ArticlePublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary'
        },
        score: {
            type: 'integer',
            title: 'Score'
        },
        kind: {
            '$ref': '#/components/schemas/ArticleKind'
        },
        categories: {
            items: {
                '$ref': '#/components/schemas/Category'
            },
            type: 'array',
            title: 'Categories'
        },
        published_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published At'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        publisher: {
            '$ref': '#/components/schemas/PublisherPublic'
        },
        tags: {
            items: {
                '$ref': '#/components/schemas/TagPublic'
            },
            type: 'array',
            title: 'Tags'
        },
        like_count: {
            type: 'integer',
            title: 'Like Count',
            default: 0
        },
        liked_by_me: {
            type: 'boolean',
            title: 'Liked By Me',
            default: false
        }
    },
    type: 'object',
    required: ['id', 'title', 'url', 'score', 'kind', 'publisher'],
    title: 'ArticlePublic'
} as const;

export const ArticlesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ArticlePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ArticlesPublic'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const CategorySchema = {
    type: 'string',
    enum: ['dev', 'models', 'research'],
    title: 'Category'
} as const;

export const FeedItemDecisionSchema = {
    properties: {
        status: {
            '$ref': '#/components/schemas/FeedItemStatus'
        },
        decision: {
            type: 'string',
            maxLength: 500,
            title: 'Decision'
        }
    },
    type: 'object',
    required: ['status', 'decision'],
    title: 'FeedItemDecision'
} as const;

export const FeedItemPublicSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        published_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published At'
        },
        feed_publisher_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Feed Publisher Id'
        },
        links: {
            items: {
                additionalProperties: true,
                type: 'object'
            },
            type: 'array',
            title: 'Links'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        fetched_at: {
            type: 'string',
            format: 'date-time',
            title: 'Fetched At'
        },
        status: {
            '$ref': '#/components/schemas/FeedItemStatus'
        },
        decision: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Decision'
        },
        feed_publisher: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Feed Publisher'
        },
        content_truncated: {
            type: 'boolean',
            title: 'Content Truncated',
            default: false
        }
    },
    type: 'object',
    required: ['url', 'title', 'id', 'fetched_at', 'status'],
    title: 'FeedItemPublic'
} as const;

export const FeedItemStatusSchema = {
    type: 'string',
    enum: ['new', 'accepted', 'rejected'],
    title: 'FeedItemStatus',
    description: `Where a feed item sits in the curation agent's loop.

The agent is non-deterministic and its runs can die halfway, so a run only
ever picks up \`new\` rows — anything already decided is never reconsidered.`
} as const;

export const FeedItemsPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/FeedItemPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'FeedItemsPublic'
} as const;

export const FetchUrlRequestSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        }
    },
    type: 'object',
    required: ['url'],
    title: 'FetchUrlRequest'
} as const;

export const FetchUrlResultSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        },
        ok: {
            type: 'boolean',
            title: 'Ok'
        },
        chars: {
            type: 'integer',
            title: 'Chars'
        },
        text: {
            type: 'string',
            title: 'Text'
        },
        truncated: {
            type: 'boolean',
            title: 'Truncated'
        }
    },
    type: 'object',
    required: ['url', 'ok', 'chars', 'text', 'truncated'],
    title: 'FetchUrlResult'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const LinkPlatformSchema = {
    type: 'string',
    enum: ['website', 'rss', 'search', 'twitter', 'github', 'substack', 'youtube', 'linkedin', 'mastodon', 'discord', 'email'],
    title: 'LinkPlatform'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const NewsletterSubscribeRequestSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        categories: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Categories'
        },
        customCategory: {
            type: 'string',
            title: 'Customcategory',
            default: ''
        },
        utm_source: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Utm Source'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'NewsletterSubscribeRequest'
} as const;

export const NewsletterSubscribeResponseSchema = {
    properties: {
        ok: {
            type: 'boolean',
            title: 'Ok',
            default: true
        }
    },
    type: 'object',
    title: 'NewsletterSubscribeResponse'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'full_name'],
    title: 'PrivateUserCreate'
} as const;

export const PublisherFacetSchema = {
    properties: {
        slug: {
            type: 'string',
            title: 'Slug'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['slug', 'name', 'count'],
    title: 'PublisherFacet'
} as const;

export const PublisherKindSchema = {
    type: 'string',
    enum: ['individual', 'company', 'community', 'media'],
    title: 'PublisherKind'
} as const;

export const PublisherPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        kind: {
            '$ref': '#/components/schemas/PublisherKind'
        },
        image: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image'
        }
    },
    type: 'object',
    required: ['id', 'slug', 'name', 'kind'],
    title: 'PublisherPublic'
} as const;

export const PublisherTypeSchema = {
    type: 'string',
    enum: ['rss', 'substack', 'search', 'hn', 'email', 'ainews', 'other'],
    title: 'PublisherType',
    description: "How the pipeline discovers a publisher's articles (its ingestion source)."
} as const;

export const PublisherUpsertSchema = {
    properties: {
        slug: {
            type: 'string',
            title: 'Slug'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        kind: {
            '$ref': '#/components/schemas/PublisherKind'
        },
        type: {
            '$ref': '#/components/schemas/PublisherType',
            default: 'other'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        image: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image'
        },
        links: {
            additionalProperties: {
                type: 'string'
            },
            propertyNames: {
                '$ref': '#/components/schemas/LinkPlatform'
            },
            type: 'object',
            title: 'Links'
        },
        trust: {
            '$ref': '#/components/schemas/TrustLevel',
            default: 'medium'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        }
    },
    type: 'object',
    required: ['slug', 'name', 'kind'],
    title: 'PublisherUpsert'
} as const;

export const SqlReadRequestSchema = {
    properties: {
        query: {
            type: 'string',
            title: 'Query'
        },
        limit: {
            anyOf: [
                {
                    type: 'integer',
                    minimum: 1
                },
                {
                    type: 'null'
                }
            ],
            title: 'Limit'
        }
    },
    type: 'object',
    required: ['query'],
    title: 'SqlReadRequest'
} as const;

export const SqlReadResultSchema = {
    properties: {
        columns: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Columns'
        },
        rows: {
            items: {
                items: {},
                type: 'array'
            },
            type: 'array',
            title: 'Rows'
        },
        row_count: {
            type: 'integer',
            title: 'Row Count'
        },
        truncated: {
            type: 'boolean',
            title: 'Truncated'
        }
    },
    type: 'object',
    required: ['columns', 'rows', 'row_count', 'truncated'],
    title: 'SqlReadResult'
} as const;

export const TagCreateSchema = {
    properties: {
        slug: {
            type: 'string',
            title: 'Slug'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        }
    },
    type: 'object',
    required: ['slug', 'name'],
    title: 'TagCreate'
} as const;

export const TagFacetSchema = {
    properties: {
        slug: {
            type: 'string',
            title: 'Slug'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['slug', 'name', 'count'],
    title: 'TagFacet'
} as const;

export const TagPublicSchema = {
    properties: {
        slug: {
            type: 'string',
            title: 'Slug'
        },
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['slug', 'name'],
    title: 'TagPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const TrustLevelSchema = {
    type: 'string',
    enum: ['low', 'medium', 'high'],
    title: 'TrustLevel'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: ['email', 'password'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;