// This file is auto-generated by @hey-api/openapi-ts

export const AnalyticsEventCreateSchema = {
    properties: {
        event: {
            type: 'string',
            title: 'Event',
            default: 'pageview'
        },
        path: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Path'
        },
        referrer: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Referrer'
        },
        visitor_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Visitor Id'
        },
        props: {
            additionalProperties: true,
            type: 'object',
            title: 'Props'
        }
    },
    type: 'object',
    title: 'AnalyticsEventCreate'
} as const;

export const AnalyticsReportSchema = {
    properties: {
        days: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Days'
        },
        totals: {
            '$ref': '#/components/schemas/ReportTotals'
        },
        daily: {
            items: {
                '$ref': '#/components/schemas/ReportDay'
            },
            type: 'array',
            title: 'Daily'
        },
        pages: {
            items: {
                '$ref': '#/components/schemas/ReportRow'
            },
            type: 'array',
            title: 'Pages'
        },
        referrers: {
            items: {
                '$ref': '#/components/schemas/ReportRow'
            },
            type: 'array',
            title: 'Referrers'
        },
        events: {
            items: {
                '$ref': '#/components/schemas/ReportRow'
            },
            type: 'array',
            title: 'Events'
        },
        articles: {
            items: {
                '$ref': '#/components/schemas/ReportArticle'
            },
            type: 'array',
            title: 'Articles'
        },
        devices: {
            items: {
                '$ref': '#/components/schemas/ReportRow'
            },
            type: 'array',
            title: 'Devices'
        }
    },
    type: 'object',
    required: ['days', 'totals', 'daily', 'pages', 'referrers', 'events', 'articles', 'devices'],
    title: 'AnalyticsReport'
} as const;

export const ArticleFacetsSchema = {
    properties: {
        publishers: {
            items: {
                '$ref': '#/components/schemas/PublisherFacet'
            },
            type: 'array',
            title: 'Publishers'
        },
        tags: {
            items: {
                '$ref': '#/components/schemas/TagFacet'
            },
            type: 'array',
            title: 'Tags'
        }
    },
    type: 'object',
    required: ['publishers', 'tags'],
    title: 'ArticleFacets'
} as const;

export const ArticleKindSchema = {
    type: 'string',
    enum: ['post', 'repo', 'paper', 'model'],
    title: 'ArticleKind'
} as const;

export const ArticlePublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        url: {
            type: 'string',
            title: 'Url'
        },
        summary: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Summary'
        },
        score: {
            type: 'integer',
            title: 'Score'
        },
        kind: {
            '$ref': '#/components/schemas/ArticleKind'
        },
        found_via: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Found Via'
        },
        published_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Published At'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        publisher: {
            '$ref': '#/components/schemas/PublisherPublic'
        },
        tags: {
            items: {
                '$ref': '#/components/schemas/TagPublic'
            },
            type: 'array',
            title: 'Tags'
        },
        like_count: {
            type: 'integer',
            title: 'Like Count',
            default: 0
        },
        liked_by_me: {
            type: 'boolean',
            title: 'Liked By Me',
            default: false
        }
    },
    type: 'object',
    required: ['id', 'title', 'url', 'score', 'kind', 'publisher'],
    title: 'ArticlePublic'
} as const;

export const ArticlesPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/ArticlePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'ArticlesPublic'
} as const;

export const FoundViaCountSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['name', 'count'],
    title: 'FoundViaCount'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MagicLoginSchema = {
    properties: {
        token: {
            type: 'string',
            maxLength: 64,
            title: 'Token'
        }
    },
    type: 'object',
    required: ['token'],
    title: 'MagicLogin'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const OriginSchema = {
    type: 'string',
    enum: ['lab', 'company', 'individual', 'media', 'repo', 'paper', 'model'],
    title: 'Origin',
    description: `The feed's "From" filter: what the article is when that is settled (a
repo, a paper, a model), otherwise who published it. Not stored; each
article falls under exactly one, see \`catalog.articles.origin_condition\`.`
} as const;

export const OriginCountSchema = {
    properties: {
        origin: {
            '$ref': '#/components/schemas/Origin'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['origin', 'count'],
    title: 'OriginCount'
} as const;

export const OriginCountsSchema = {
    properties: {
        since: {
            type: 'string',
            format: 'date-time',
            title: 'Since'
        },
        total: {
            type: 'integer',
            title: 'Total'
        },
        origins: {
            items: {
                '$ref': '#/components/schemas/OriginCount'
            },
            type: 'array',
            title: 'Origins'
        },
        unlabelled: {
            type: 'integer',
            title: 'Unlabelled'
        },
        found_via: {
            items: {
                '$ref': '#/components/schemas/FoundViaCount'
            },
            type: 'array',
            title: 'Found Via'
        }
    },
    type: 'object',
    required: ['since', 'total', 'origins', 'unlabelled', 'found_via'],
    title: 'OriginCounts'
} as const;

export const PublisherFacetSchema = {
    properties: {
        slug: {
            type: 'string',
            title: 'Slug'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['slug', 'name', 'count'],
    title: 'PublisherFacet'
} as const;

export const PublisherKindSchema = {
    type: 'string',
    enum: ['lab', 'company', 'individual', 'media', 'community', 'unknown'],
    title: 'PublisherKind'
} as const;

export const PublisherPublicSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        slug: {
            type: 'string',
            title: 'Slug'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        kind: {
            '$ref': '#/components/schemas/PublisherKind'
        },
        image: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image'
        }
    },
    type: 'object',
    required: ['id', 'slug', 'name', 'kind'],
    title: 'PublisherPublic'
} as const;

export const ReportArticleSchema = {
    properties: {
        article_id: {
            type: 'string',
            title: 'Article Id'
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        clicks: {
            type: 'integer',
            title: 'Clicks'
        },
        visitors: {
            type: 'integer',
            title: 'Visitors'
        }
    },
    type: 'object',
    required: ['article_id', 'title', 'clicks', 'visitors'],
    title: 'ReportArticle'
} as const;

export const ReportDaySchema = {
    properties: {
        day: {
            type: 'string',
            format: 'date',
            title: 'Day'
        },
        visitors: {
            type: 'integer',
            title: 'Visitors'
        },
        pageviews: {
            type: 'integer',
            title: 'Pageviews'
        }
    },
    type: 'object',
    required: ['day', 'visitors', 'pageviews'],
    title: 'ReportDay'
} as const;

export const ReportRowSchema = {
    properties: {
        label: {
            type: 'string',
            title: 'Label'
        },
        count: {
            type: 'integer',
            title: 'Count'
        },
        visitors: {
            type: 'integer',
            title: 'Visitors'
        }
    },
    type: 'object',
    required: ['label', 'count', 'visitors'],
    title: 'ReportRow'
} as const;

export const ReportTotalsSchema = {
    properties: {
        visitors: {
            type: 'integer',
            title: 'Visitors'
        },
        pageviews: {
            type: 'integer',
            title: 'Pageviews'
        },
        returning_visitors: {
            type: 'integer',
            title: 'Returning Visitors'
        },
        article_clicks: {
            type: 'integer',
            title: 'Article Clicks'
        },
        admin_pageviews: {
            type: 'integer',
            title: 'Admin Pageviews'
        },
        bot_pageviews: {
            type: 'integer',
            title: 'Bot Pageviews'
        }
    },
    type: 'object',
    required: ['visitors', 'pageviews', 'returning_visitors', 'article_clicks', 'admin_pageviews', 'bot_pageviews'],
    title: 'ReportTotals'
} as const;

export const SignInRequestSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'SignInRequest'
} as const;

export const TagFacetSchema = {
    properties: {
        slug: {
            type: 'string',
            title: 'Slug'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['slug', 'name', 'count'],
    title: 'TagFacet'
} as const;

export const TagPublicSchema = {
    properties: {
        slug: {
            type: 'string',
            title: 'Slug'
        },
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['slug', 'name'],
    title: 'TagPublic'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        }
    },
    type: 'object',
    required: ['email', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        utm_source: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Utm Source'
        }
    },
    type: 'object',
    required: ['email'],
    title: 'UserRegister'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;