// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { AgentListFeedItemsData, AgentListFeedItemsResponse, AgentMarkFeedItemData, AgentMarkFeedItemResponse, AgentListPublishersData, AgentListPublishersResponse, AgentUpsertPublisherData, AgentUpsertPublisherResponse, AgentListTagsResponse, AgentCreateTagData, AgentCreateTagResponse, AgentSqlReadData, AgentSqlReadResponse, AgentFetchUrlData, AgentFetchUrlResponse, AgentCreateArticleData, AgentCreateArticleResponse, AnalyticsCollectEventData, AnalyticsCollectEventResponse, ArticlesReadArticlesData, ArticlesReadArticlesResponse, ArticlesSearchArticlesData, ArticlesSearchArticlesResponse, ArticlesArticleFacetsData, ArticlesArticleFacetsResponse, ArticlesSearchPublishersData, ArticlesSearchPublishersResponse, ArticlesSearchTagsData, ArticlesSearchTagsResponse, ArticlesArticleStatsResponse, LikesLikeArticleData, LikesLikeArticleResponse, LikesUnlikeArticleData, LikesUnlikeArticleResponse, LikesReadLikedArticlesResponse, LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, NewsletterSubscribeData, NewsletterSubscribeResponse2, PrivateCreateUserData, PrivateCreateUserResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsTestEmailData, UtilsTestEmailResponse, UtilsHealthCheckResponse } from './types.gen';

export class AgentService {
    /**
     * List Feed Items
     * The inbox, newest first. `count` is every item in that status, not just
     * the ones on this page — it is how the agent knows how much is left.
     * @param data The data for the request.
     * @param data.status
     * @param data.limit
     * @param data.contentChars
     * @returns FeedItemsPublic Successful Response
     * @throws ApiError
     */
    public static listFeedItems(data: AgentListFeedItemsData = {}): CancelablePromise<AgentListFeedItemsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/agent/feed-items',
            query: {
                status: data.status,
                limit: data.limit,
                content_chars: data.contentChars
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Mark Feed Item
     * Record the agent's verdict. Decided items never come back in a `new`
     * batch, which is what makes a half-finished run safe to just re-run.
     * @param data The data for the request.
     * @param data.itemId
     * @param data.requestBody
     * @returns FeedItemPublic Successful Response
     * @throws ApiError
     */
    public static markFeedItem(data: AgentMarkFeedItemData): CancelablePromise<AgentMarkFeedItemResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/agent/feed-items/{item_id}/decision',
            path: {
                item_id: data.itemId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Publishers
     * @param data The data for the request.
     * @param data.q
     * @param data.limit
     * @returns AgentPublisher Successful Response
     * @throws ApiError
     */
    public static listPublishers(data: AgentListPublishersData = {}): CancelablePromise<AgentListPublishersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/agent/publishers',
            query: {
                q: data.q,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Upsert Publisher
     * Create or update a publisher by slug.
     *
     * This is how a first-party source the agent found mid-run becomes an
     * attribution target. Leave the links empty and the pipeline never polls it —
     * it exists only so the article has the right byline.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns AgentPublisher Successful Response
     * @throws ApiError
     */
    public static upsertPublisher(data: AgentUpsertPublisherData): CancelablePromise<AgentUpsertPublisherResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/agent/publishers',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Tags
     * The whole controlled vocabulary — slug, name, and when to apply it.
     * @returns AgentTag Successful Response
     * @throws ApiError
     */
    public static listTags(): CancelablePromise<AgentListTagsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/agent/tags'
        });
    }
    
    /**
     * Create Tag
     * Mint a vocabulary entry. Rare by design: a tag that fits three articles
     * a year is a worse filter than no tag.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns AgentTag Successful Response
     * @throws ApiError
     */
    public static createTag(data: AgentCreateTagData): CancelablePromise<AgentCreateTagResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/agent/tags',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Sql Read
     * Run one SELECT and return its rows.
     *
     * Open on purpose: the agent asking "what have we published from this
     * publisher lately?" should not need a new endpoint every time it thinks of
     * a new question. Bounded by a read-only transaction, a statement timeout,
     * and a row cap.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns SqlReadResult Successful Response
     * @throws ApiError
     */
    public static sqlRead(data: AgentSqlReadData): CancelablePromise<AgentSqlReadResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/agent/sql',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Fetch Url
     * Fetch one URL and return its readable text.
     *
     * Direct first, residential proxy on failure, trafilatura for the extract —
     * the same path the pipeline uses on its own sources. An empty result is an
     * answer, not an error: plenty of pages will not give us text, and the agent
     * still has the title to judge on.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns FetchUrlResult Successful Response
     * @throws ApiError
     */
    public static fetchUrl(data: AgentFetchUrlData): CancelablePromise<AgentFetchUrlResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/agent/fetch-url',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Article
     * Publish one article.
     *
     * The agent never sends a vector and never sends SQL: it sends the fields it
     * judged, and this validates them, embeds server-side, inserts, and links the
     * tags. A duplicate URL is a 409 rather than a second row.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns AgentArticleCreated Successful Response
     * @throws ApiError
     */
    public static createArticle(data: AgentCreateArticleData): CancelablePromise<AgentCreateArticleResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/agent/articles',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class AnalyticsService {
    /**
     * Collect Event
     * Record one analytics event. Public and fire-and-forget (returns 204).
     *
     * Attaches the user id when the request carries a valid bearer token;
     * otherwise the event is anonymous. No dashboard — query the table in SQL.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns void Successful Response
     * @throws ApiError
     */
    public static collectEvent(data: AnalyticsCollectEventData): CancelablePromise<AnalyticsCollectEventResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/analytics/collect',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class ArticlesService {
    /**
     * Read Articles
     * @param data The data for the request.
     * @param data.limit
     * @param data.since
     * @param data.q
     * @param data.minScore
     * @param data.category
     * @param data.kind
     * @param data.tag
     * @param data.publisher
     * @param data.sort
     * @returns ArticlesPublic Successful Response
     * @throws ApiError
     */
    public static readArticles(data: ArticlesReadArticlesData = {}): CancelablePromise<ArticlesReadArticlesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/articles/',
            query: {
                limit: data.limit,
                since: data.since,
                q: data.q,
                min_score: data.minScore,
                category: data.category,
                kind: data.kind,
                tag: data.tag,
                publisher: data.publisher,
                sort: data.sort
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Search Articles
     * @param data The data for the request.
     * @param data.q
     * @param data.limit
     * @returns ArticlesPublic Successful Response
     * @throws ApiError
     */
    public static searchArticles(data: ArticlesSearchArticlesData): CancelablePromise<ArticlesSearchArticlesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/articles/search',
            query: {
                q: data.q,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Article Facets
     * @param data The data for the request.
     * @param data.limit
     * @returns ArticleFacets Successful Response
     * @throws ApiError
     */
    public static articleFacets(data: ArticlesArticleFacetsData = {}): CancelablePromise<ArticlesArticleFacetsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/articles/facets',
            query: {
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Search Publishers
     * @param data The data for the request.
     * @param data.q
     * @param data.limit
     * @returns PublisherFacet Successful Response
     * @throws ApiError
     */
    public static searchPublishers(data: ArticlesSearchPublishersData = {}): CancelablePromise<ArticlesSearchPublishersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/articles/publishers',
            query: {
                q: data.q,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Search Tags
     * @param data The data for the request.
     * @param data.q
     * @param data.limit
     * @returns TagFacet Successful Response
     * @throws ApiError
     */
    public static searchTags(data: ArticlesSearchTagsData = {}): CancelablePromise<ArticlesSearchTagsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/articles/tags',
            query: {
                q: data.q,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Article Stats
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static articleStats(): CancelablePromise<ArticlesArticleStatsResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/articles/stats'
        });
    }
}

export class LikesService {
    /**
     * Like Article
     * @param data The data for the request.
     * @param data.articleId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static likeArticle(data: LikesLikeArticleData): CancelablePromise<LikesLikeArticleResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/articles/{article_id}/like',
            path: {
                article_id: data.articleId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Unlike Article
     * @param data The data for the request.
     * @param data.articleId
     * @returns unknown Successful Response
     * @throws ApiError
     */
    public static unlikeArticle(data: LikesUnlikeArticleData): CancelablePromise<LikesUnlikeArticleResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/articles/{article_id}/like',
            path: {
                article_id: data.articleId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read Liked Articles
     * @returns ArticlesPublic Successful Response
     * @throws ApiError
     */
    public static readLikedArticles(): CancelablePromise<LikesReadLikedArticlesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/me/liked-articles'
        });
    }
}

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class NewsletterService {
    /**
     * Subscribe
     * @param data The data for the request.
     * @param data.requestBody
     * @returns NewsletterSubscribeResponse Successful Response
     * @throws ApiError
     */
    public static subscribe(data: NewsletterSubscribeData): CancelablePromise<NewsletterSubscribeResponse2> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/newsletter/subscribe',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PrivateService {
    /**
     * Create User
     * Create a new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: PrivateCreateUserData): CancelablePromise<PrivateCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/private/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Test Email
     * Test emails.
     * @param data The data for the request.
     * @param data.emailTo
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static testEmail(data: UtilsTestEmailData): CancelablePromise<UtilsTestEmailResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/utils/test-email/',
            query: {
                email_to: data.emailTo
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}