// This file is auto-generated by @hey-api/openapi-ts

export type AgentArticleCreate = {
    url: string;
    title: string;
    publisher_slug: string;
    score: number;
    kind?: ArticleKind;
    categories?: Array<Category>;
    summary?: (string | null);
    content?: (string | null);
    published_at?: (string | null);
    tags?: Array<(string)>;
};

export type AgentArticleCreated = {
    id: number;
    url: string;
    title: string;
    score: number;
    publisher_slug: string;
    tags: Array<(string)>;
    embedded: boolean;
};

export type AgentPublisher = {
    id: number;
    slug: string;
    name: string;
    kind: PublisherKind;
    type: PublisherType;
    trust: TrustLevel;
    is_active: boolean;
    description?: (string | null);
    links?: {
        [key: string]: (string);
    };
};

export type AgentTag = {
    id: number;
    slug: string;
    name: string;
    description?: (string | null);
};

export type AnalyticsEventCreate = {
    event?: string;
    path?: (string | null);
    referrer?: (string | null);
    visitor_id?: (string | null);
    props?: {
        [key: string]: unknown;
    };
};

export type ArticleFacets = {
    publishers: Array<PublisherFacet>;
    tags: Array<TagFacet>;
};

export type ArticleKind = 'blog' | 'product' | 'announcement' | 'repo' | 'paper' | 'model';

export type ArticlePublic = {
    id: number;
    title: string;
    url: string;
    summary?: (string | null);
    score: number;
    kind: ArticleKind;
    categories?: Array<Category>;
    published_at?: (string | null);
    created_at?: (string | null);
    publisher: PublisherPublic;
    tags?: Array<TagPublic>;
    like_count?: number;
    liked_by_me?: boolean;
};

export type ArticlesPublic = {
    data: Array<ArticlePublic>;
    count: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Category = 'dev' | 'models' | 'research';

export type FeedItemDecision = {
    status: FeedItemStatus;
    decision: string;
};

export type FeedItemPublic = {
    url: string;
    title: string;
    content?: (string | null);
    published_at?: (string | null);
    feed_publisher_id?: (number | null);
    links?: Array<{
        [key: string]: unknown;
    }>;
    id: number;
    fetched_at: string;
    status: FeedItemStatus;
    decision?: (string | null);
    feed_publisher?: (string | null);
    content_truncated?: boolean;
};

export type FeedItemsPublic = {
    data: Array<FeedItemPublic>;
    count: number;
};

/**
 * Where a feed item sits in the curation agent's loop.
 *
 * The agent is non-deterministic and its runs can die halfway, so a run only
 * ever picks up `new` rows — anything already decided is never reconsidered.
 */
export type FeedItemStatus = 'new' | 'accepted' | 'rejected';

export type FetchUrlRequest = {
    url: string;
};

export type FetchUrlResult = {
    url: string;
    ok: boolean;
    chars: number;
    text: string;
    truncated: boolean;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type LinkPlatform = 'website' | 'rss' | 'search' | 'twitter' | 'github' | 'substack' | 'youtube' | 'linkedin' | 'mastodon' | 'discord' | 'email';

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NewsletterSubscribeRequest = {
    email: string;
    categories?: Array<(string)>;
    customCategory?: string;
    utm_source?: (string | null);
};

export type NewsletterSubscribeResponse = {
    ok?: boolean;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type PublisherFacet = {
    slug: string;
    name: string;
    count: number;
};

export type PublisherKind = 'individual' | 'company' | 'community' | 'media';

export type PublisherPublic = {
    id: number;
    slug: string;
    name: string;
    kind: PublisherKind;
    image?: (string | null);
};

/**
 * How the pipeline discovers a publisher's articles (its ingestion source).
 */
export type PublisherType = 'rss' | 'substack' | 'search' | 'hn' | 'email' | 'ainews' | 'other';

export type PublisherUpsert = {
    slug: string;
    name: string;
    kind: PublisherKind;
    type?: PublisherType;
    description?: (string | null);
    image?: (string | null);
    links?: {
        [key: string]: (string);
    };
    trust?: TrustLevel;
    is_active?: boolean;
};

export type SqlReadRequest = {
    query: string;
    limit?: (number | null);
};

export type SqlReadResult = {
    columns: Array<(string)>;
    rows: Array<Array<unknown>>;
    row_count: number;
    truncated: boolean;
};

export type TagCreate = {
    slug: string;
    name: string;
    description?: (string | null);
};

export type TagFacet = {
    slug: string;
    name: string;
    count: number;
};

export type TagPublic = {
    slug: string;
    name: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type TrustLevel = 'low' | 'medium' | 'high';

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AgentListFeedItemsData = {
    contentChars?: number;
    limit?: number;
    status?: FeedItemStatus;
};

export type AgentListFeedItemsResponse = (FeedItemsPublic);

export type AgentMarkFeedItemData = {
    itemId: number;
    requestBody: FeedItemDecision;
};

export type AgentMarkFeedItemResponse = (FeedItemPublic);

export type AgentListPublishersData = {
    limit?: number;
    q?: (string | null);
};

export type AgentListPublishersResponse = (Array<AgentPublisher>);

export type AgentUpsertPublisherData = {
    requestBody: PublisherUpsert;
};

export type AgentUpsertPublisherResponse = (AgentPublisher);

export type AgentListTagsResponse = (Array<AgentTag>);

export type AgentCreateTagData = {
    requestBody: TagCreate;
};

export type AgentCreateTagResponse = (AgentTag);

export type AgentSqlReadData = {
    requestBody: SqlReadRequest;
};

export type AgentSqlReadResponse = (SqlReadResult);

export type AgentFetchUrlData = {
    requestBody: FetchUrlRequest;
};

export type AgentFetchUrlResponse = (FetchUrlResult);

export type AgentCreateArticleData = {
    requestBody: AgentArticleCreate;
};

export type AgentCreateArticleResponse = (AgentArticleCreated);

export type AnalyticsCollectEventData = {
    requestBody: AnalyticsEventCreate;
};

export type AnalyticsCollectEventResponse = (void);

export type ArticlesReadArticlesData = {
    category?: (string | null);
    kind?: (string | null);
    limit?: number;
    minScore?: (number | null);
    publisher?: (string | null);
    q?: (string | null);
    since?: (string | null);
    sort?: string;
    tag?: (string | null);
};

export type ArticlesReadArticlesResponse = (ArticlesPublic);

export type ArticlesSearchArticlesData = {
    limit?: number;
    q: string;
};

export type ArticlesSearchArticlesResponse = (ArticlesPublic);

export type ArticlesArticleFacetsData = {
    limit?: number;
};

export type ArticlesArticleFacetsResponse = (ArticleFacets);

export type ArticlesSearchPublishersData = {
    limit?: number;
    q?: (string | null);
};

export type ArticlesSearchPublishersResponse = (Array<PublisherFacet>);

export type ArticlesSearchTagsData = {
    limit?: number;
    q?: (string | null);
};

export type ArticlesSearchTagsResponse = (Array<TagFacet>);

export type ArticlesArticleStatsResponse = (unknown);

export type LikesLikeArticleData = {
    articleId: number;
};

export type LikesLikeArticleResponse = (unknown);

export type LikesUnlikeArticleData = {
    articleId: number;
};

export type LikesUnlikeArticleResponse = (unknown);

export type LikesReadLikedArticlesResponse = (ArticlesPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type NewsletterSubscribeData = {
    requestBody: NewsletterSubscribeRequest;
};

export type NewsletterSubscribeResponse2 = (NewsletterSubscribeResponse);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);