// This file is auto-generated by @hey-api/openapi-ts

export type AnalyticsEventCreate = {
    event?: string;
    path?: (string | null);
    referrer?: (string | null);
    visitor_id?: (string | null);
    props?: {
        [key: string]: unknown;
    };
};

export type ArticleFacets = {
    publishers: Array<PublisherFacet>;
    tags: Array<TagFacet>;
};

export type ArticleKind = 'post' | 'repo' | 'paper' | 'model';

export type ArticlePublic = {
    id: number;
    title: string;
    url: string;
    summary?: (string | null);
    score: number;
    kind: ArticleKind;
    found_via?: (string | null);
    published_at?: (string | null);
    created_at?: (string | null);
    publisher: PublisherPublic;
    tags?: Array<TagPublic>;
    like_count?: number;
    liked_by_me?: boolean;
};

export type ArticlesPublic = {
    data: Array<ArticlePublic>;
    count: number;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type MagicLogin = {
    token: string;
};

export type Message = {
    message: string;
};

/**
 * The feed's "From" filter: what the article is when that is settled (a
 * repo, a paper, a model), otherwise who published it. Not stored; each
 * article falls under exactly one, see `catalog.articles.origin_condition`.
 */
export type Origin = 'lab' | 'company' | 'individual' | 'media' | 'repo' | 'paper' | 'model';

export type PublisherFacet = {
    slug: string;
    name: string;
    count: number;
};

export type PublisherKind = 'lab' | 'company' | 'individual' | 'media' | 'community' | 'unknown';

export type PublisherPublic = {
    id: number;
    slug: string;
    name: string;
    kind: PublisherKind;
    image?: (string | null);
};

export type SignInRequest = {
    email: string;
};

export type TagFacet = {
    slug: string;
    name: string;
    count: number;
};

export type TagPublic = {
    slug: string;
    name: string;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    utm_source?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AnalyticsCollectEventData = {
    requestBody: AnalyticsEventCreate;
};

export type AnalyticsCollectEventResponse = (void);

export type ArticlesReadArticlesData = {
    kind?: (Array<(string)> | null);
    limit?: number;
    minScore?: (number | null);
    origin?: (Origin | null);
    publisher?: (string | null);
    q?: (string | null);
    since?: (string | null);
    sort?: string;
    tag?: (Array<(string)> | null);
};

export type ArticlesReadArticlesResponse = (ArticlesPublic);

export type ArticlesSearchArticlesData = {
    limit?: number;
    q: string;
};

export type ArticlesSearchArticlesResponse = (ArticlesPublic);

export type ArticlesArticleFacetsData = {
    limit?: number;
};

export type ArticlesArticleFacetsResponse = (ArticleFacets);

export type ArticlesSearchPublishersData = {
    limit?: number;
    q?: (string | null);
};

export type ArticlesSearchPublishersResponse = (Array<PublisherFacet>);

export type ArticlesSearchTagsData = {
    limit?: number;
    q?: (string | null);
};

export type ArticlesSearchTagsResponse = (Array<TagFacet>);

export type ArticlesArticleStatsResponse = ({
    [key: string]: (number | string | null);
});

export type LikesLikeArticleData = {
    articleId: number;
};

export type LikesLikeArticleResponse = ({
    [key: string]: (boolean);
});

export type LikesUnlikeArticleData = {
    articleId: number;
};

export type LikesUnlikeArticleResponse = ({
    [key: string]: (boolean);
});

export type LikesReadLikedArticlesResponse = (ArticlesPublic);

export type LoginRequestSignInLinkData = {
    requestBody: SignInRequest;
};

export type LoginRequestSignInLinkResponse = (Message);

export type LoginLoginWithLinkData = {
    requestBody: MagicLogin;
};

export type LoginLoginWithLinkResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);