// This file is auto-generated by @hey-api/openapi-ts

export type AnalyticsEventCreate = {
    event?: string;
    path?: (string | null);
    referrer?: (string | null);
    visitor_id?: (string | null);
    props?: {
        [key: string]: unknown;
    };
};

export type ArticleFacets = {
    publishers: Array<PublisherFacet>;
    categories: Array<CategoryFacet>;
};

export type ArticleKind = 'blog' | 'product' | 'announcement' | 'repo' | 'paper' | 'model';

export type ArticlePublic = {
    id: number;
    title: string;
    url: string;
    excerpt?: (string | null);
    kind: ArticleKind;
    categories?: Array<CategoryPublic>;
    published_at?: (string | null);
    created_at?: (string | null);
    publisher: PublisherPublic;
    like_count?: number;
    liked_by_me?: boolean;
};

export type ArticlesPublic = {
    data: Array<ArticlePublic>;
    count: number;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type CategoryFacet = {
    slug: string;
    name: string;
    count: number;
};

export type CategoryPublic = {
    slug: string;
    name: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type NewsletterSubscribeRequest = {
    email: string;
    categories?: Array<(string)>;
    customCategory?: string;
    utm_source?: (string | null);
};

export type NewsletterSubscribeResponse = {
    ok?: boolean;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type PublisherFacet = {
    slug: string;
    name: string;
    count: number;
};

export type PublisherKind = 'individual' | 'company' | 'community' | 'media';

export type PublisherPublic = {
    id: number;
    slug: string;
    name: string;
    kind: PublisherKind;
    image?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AnalyticsCollectEventData = {
    requestBody: AnalyticsEventCreate;
};

export type AnalyticsCollectEventResponse = (void);

export type ArticlesReadArticlesData = {
    category?: (string | null);
    kind?: (string | null);
    limit?: number;
    publisher?: (string | null);
    q?: (string | null);
    since?: (string | null);
    sort?: string;
};

export type ArticlesReadArticlesResponse = (ArticlesPublic);

export type ArticlesSearchArticlesData = {
    limit?: number;
    q: string;
};

export type ArticlesSearchArticlesResponse = (ArticlesPublic);

export type ArticlesArticleFacetsData = {
    limit?: number;
};

export type ArticlesArticleFacetsResponse = (ArticleFacets);

export type ArticlesSearchPublishersData = {
    limit?: number;
    q?: (string | null);
};

export type ArticlesSearchPublishersResponse = (Array<PublisherFacet>);

export type ArticlesSearchCategoriesData = {
    limit?: number;
    q?: (string | null);
};

export type ArticlesSearchCategoriesResponse = (Array<CategoryFacet>);

export type ArticlesArticleStatsResponse = (unknown);

export type LikesLikeArticleData = {
    articleId: number;
};

export type LikesLikeArticleResponse = (unknown);

export type LikesUnlikeArticleData = {
    articleId: number;
};

export type LikesUnlikeArticleResponse = (unknown);

export type LikesReadLikedArticlesResponse = (ArticlesPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type NewsletterSubscribeData = {
    requestBody: NewsletterSubscribeRequest;
};

export type NewsletterSubscribeResponse2 = (NewsletterSubscribeResponse);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);